apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "twbc-nft-api-service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-max-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    kubernetes.io/tls-acme: "true"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    {{- include "twbc-nft-api-service.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ include "twbc-nft-api-service.fullname" . }}-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name:  {{ include "twbc-nft-api-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
