AWSTemplateFormatVersion: "2010-09-09"
Description: Create bucket to store nft images
Resources:
  S3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: twbc-nft-images
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins: 
              - "*"
  BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowListPutObjects
              Effect: Allow
              Principal:
                AWS:
                  - !Sub arn:aws-cn:iam::${AWS::AccountId}:role/TWBCEksWorkerRole
              Action:
                - s3:List*
                - s3:get*
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub ${S3.Arn}/*